### ISSUE TITLE
Reward Center Accept Offer Instruction

### ISSUE THREAD

**Issue by kespinola** [holaplex/reward-center-program#16]
### Goal
Dapps are able to issue an accept_offer instruction that takes the offer, creates the seller trade state, and then issues execute sale without creating the rewards listing.

The instruction should make CPI calls to [auctioneer_sell](https://github.com/holaplex/reward-center-program/blob/main/program/src/listings/create/mod.rs#L242) and then call [execute_sale::handler](https://github.com/holaplex/reward-center-program/blob/main/program/src/execute_sale/mod.rs#L281)

**Comment by sunguru98** [comment]
Can we close this @kespinola?

**Comment by kespinola** [comment]
done.
